name: Update data

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Generate data
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 15.x
    - run: node generate.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit & Push Generated Data
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Actions Auto Build"
        git add -f .
        git commit -m "docs: generate documents" || true
        git push --force origin HEAD:refs/heads/main
